### ISSUE TITLE
Beta Ingress API, extensions/v1beta1, has been removed in kube 1.22

### ISSUE THREAD

**Issue by JanetSch** [blueperf/acmeair-mainservice-java#35]
In Kubernetes 1.22 the beta Ingress API, extensions/v1beta1, has been removed and replaced with networking.k8s.io/v1 Ingress API.

https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/#api-changes

Acmeair uses this Ingress API in several yaml files that I can see.

The kubernetes container service uses acmeair as a benchmark and has just started testing on 1.22 and found that it no longer works.

**Comment by jdmcclur** [comment]
I see, I'll take a look.

**Comment by JanetSch** [comment]
Thanks. I've found with my tests that along with the apiVersion: networking.k8s.io/v1 change I needed to change the paths section in the yaml to this format too:

```
http:
      paths:
      - path: /OLBServiceOrchestratorWeb
        pathType: "Prefix"
        backend:
          service:
            name: olb-app-service
            port:
              number:  9080
      

```
